### ISSUE TITLE
CI failed AElf.Cryptography.Tests.AElfKeyStoreTests.Account_Create_And_Open 

### ISSUE THREAD

**Issue by loning** [AElfProject/AElf#935] opened 2019-02-25 14:19 UTC
[xUnit.net 00:00:03.82]     AElf.Cryptography.Tests.AElfKeyStoreTests.Account_Create_And_Open [FAIL]
Total tests: 9. Passed: 9. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.9438 Seconds
Calculating coverage result...
Failed   AElf.Cryptography.Tests.AElfKeyStoreTests.Account_Create_And_Open
Error Message:
 Shouldly.ShouldAssertException : keyPair1.PrivateKey
    should be
[0, 133, 182, 136, 164, 87, 24, 197, 198, 73, 215, 174, 244, 36, 247, 47, 25, 147, 107, 206, 157, 219, 118, 89, 32, 173, 165, 44, 38, 33, 175, 114]
    but was
[133, 182, 136, 164, 87, 24, 197, 198, 73, 215, 174, 244, 36, 247, 47, 25, 147, 107, 206, 157, 219, 118, 89, 32, 173, 165, 44, 38, 33, 175, 114]
    difference
[*133*, *182*, *136*, *164*, *87*, *24*, *197*, *198*, *73*, *215*, *174*, *244*, *36*, *247*, *47*, *25*, *147*, *107*, *206*, *157*, *219*, *118*, *89*, *32*, *173*, *165*, *44*, *38*, *33*, *175*, *114*, *]
Stack Trace:
   at AElf.Cryptography.Tests.AElfKeyStoreTests.Account_Create_And_Open() in /home/travis/build/AElfProject/AElf/AElf.Cryptography.Tests/AElfKeyStoreTests.cs:line 39

https://travis-ci.org/AElfProject/AElf/builds/498177743?utm_source=github_status&utm_medium=notification

https://github.com/AElfProject/AElf/pull/934/commits/a315320b380db41c3160ee2ddb6701cf9ac083ec

no changes to Account_Create_And_Open but it failed

**Comment by loning** [comment] 2019-02-27 07:52
https://travis-ci.org/AElfProject/AElf/builds/499116308?utm_source=github_status&utm_medium=notification

@rosona @EricBlack , this test failed may cause CI failed, please fix it **APSP**

**Comment by EricBlack** [comment] 2019-02-27 11:28
> https://travis-ci.org/AElfProject/AElf/builds/499116308?utm_source=github_status&utm_medium=notification
> 
> @rosona @EricBlack , this test failed may cause CI failed, please fix it **APSP**

This issue caused by when generate PrivateKey array first item value is '0', and after read account from file, the PrivateKey array '0' value was removed, and array length also changed from 32 to 31. But both two PrivateKey generated PublicKey and Address are the same.

**Comment by EricBlack** [comment] 2019-02-28 02:05
Close this due to case fixed.

**Closed** 2019-02-28 02:05 UTC
Labels: P1, bug
